// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IRiCodeLine: typeof import('~icons/ri/code-line')['default']
    IRiFileCopyLine: typeof import('~icons/ri/file-copy-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VpApp: typeof import('./.vitepress/vitepress/components/vp-app.vue')['default']
    VpContent: typeof import('./.vitepress/vitepress/components/vp-content.vue')['default']
    VpDemo: typeof import('./.vitepress/vitepress/components/vp-demo.vue')['default']
    VpDocContent: typeof import('./.vitepress/vitepress/components/vp-doc-content.vue')['default']
    VpExample: typeof import('./.vitepress/vitepress/components/demo/vp-example.vue')['default']
    VpNotFound: typeof import('./.vitepress/vitepress/components/vp-not-found.vue')['default']
    VpSourceCode: typeof import('./.vitepress/vitepress/components/demo/vp-source-code.vue')['default']
  }
}
